deployment:
  tasks:
    # Next line defines a DEPLOYPATH with the path to the document root of your website so that you will not have to enter it in each command manually:
    - export DEPLOYPATH=react-1.easypalengkepampang.com
    - cp -r * $DEPLOYPATH
  remote: origin
  branch: master
